### ISSUE TITLE
Not working examples of Redux DevTools

### ISSUE THREAD

**Issue by hex13** [zalmoxisus/zalmoxisus.github.io#1]
There are wrong urls for examples:
1. go to:
   http://zalmoxisus.github.io/redux-devtools-extension/FAQ.html#how-to-get-it-work
   click two links from:
   `Counter or TodoMVC demo.`
   you will have 404 error

Links refer to these urls:
http://zalmoxisus.github.io/redux-devtools-extension/examples/counter/
http://zalmoxisus.github.io/redux-devtools-extension/examples/todomvc/
and in reality examples are on this urls:
http://zalmoxisus.github.io/examples/counter/
http://zalmoxisus.github.io/examples/todomvc/
1. first example doesn't work, it has errors in console (Google Chrome):

```
Uncaught TypeError: (0 , _configureStore.isMonitorAction) is not a function(…)
3http://zalmoxisus.github.io/__webpack_hmr Failed to load resource: the server responded with a status of 404 (Not Found)
/__webpack_hmr:1 GET http://zalmoxisus.github.io/__webpack_hmr 
/__webpack_hmr:1 GET http://zalmoxisus.github.io/__webpack_hmr 
/__webpack_hmr:1 GET http://zalmoxisus.github.io/__webpack_hmr 
```

second example does display "list of todos" but also has errors in console:
`/__webpack_hmr:1 GET http://zalmoxisus.github.io/__webpack_hmr`
(it's red GET: 

![image](https://cloud.githubusercontent.com/assets/3883359/19425385/16f92454-9432-11e6-89f9-214c596024ae.png)
)

Setting: I don't have ReduxDevTools installed in browser, I don't know if this could be cause of errors (but  these TodoMVC and Counter examples should inform me what is wrong anyway).

**Comment by zalmoxisus** [comment]
Thanks for the report! I updated the links and examples.
